# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: CI

on: [pull_request, push]

jobs:
  make:
    runs-on: ubuntu-latest
    container: gentoo/stage3
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        make check
